image: python:3.11
buildCommand: |
  pip cache purge && \
  rm -rf .venv && \
  python -m venv .venv && \
  source .venv/bin/activate && \
  pip install --upgrade pip setuptools wheel && \
  pip install -r requirements.txt
startCommand: |
  source .venv/bin/activate && \
  python app.py
